name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Private 레포 clone
      uses: actions/checkout@v3
      with:
        repository: KIMSSEUNG/animal-chat-server
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        path: app

    - name: 🛠️ JDK 설정
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 📦 빌드
      run: |
        cd app
        ./gradlew clean bootJar

    - name: 🚀 EC2에 배포
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app/build/libs/*.jar"
        target: "/home/ubuntu/animal-chat"

    - name: 🔁 EC2에서 실행 (기존 프로세스 종료 포함)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pkill -f 'java.*animalChat' || true
          nohup java -jar /home/ubuntu/animal-chat/*.jar > server.log 2>&1 &
